version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 80:8080
    depends_on:
      - database
    environment:
      - DRUPAL_DATABASE_HOST=database
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
    volumes:
      - drupal_data:/bitnami

  database:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=drupal
      - MARIADB_PASSWORD=drupal
      - MARIADB_DATABASE=drupal
    volumes:
      - db_data:/bitnami

  webserver:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - drupal_data:/usr/share/nginx/html

  certbot:
    image: certbot

volumes:
  drupal_data:
  db_data:
